# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAcademic',
            fields=[
                ('pass_year_10', models.IntegerField(blank=True, db_column='Pass_Year_10', null=True)),
                ('cgpa_per_10', models.DecimalField(blank=True, db_column='Cgpa_Per_10', decimal_places=1, max_digits=5, null=True)),
                ('pass_year_12', models.IntegerField(blank=True, db_column='Pass_Year_12', null=True)),
                ('cgpa_per_12', models.DecimalField(blank=True, db_column='Cgpa_Per_12', decimal_places=1, max_digits=5, null=True)),
                ('pass_year_dip', models.IntegerField(blank=True, db_column='Pass_Year_Dip', null=True)),
                ('cgpa_per_dip', models.DecimalField(blank=True, db_column='Cgpa_Per_Dip', decimal_places=1, max_digits=5, null=True)),
                ('pass_year_ug', models.IntegerField(blank=True, db_column='Pass_Year_Ug', null=True)),
                ('cgpa_per_ug', models.DecimalField(blank=True, db_column='Cgpa_Per_Ug', decimal_places=1, max_digits=5, null=True)),
                ('pass_year_pg', models.IntegerField(blank=True, db_column='Pass_Year_Pg', null=True)),
                ('cgpa_per_pg', models.DecimalField(blank=True, db_column='Cgpa_Per_Pg', decimal_places=1, max_digits=5, null=True)),
                ('area_spl_pg', models.IntegerField(blank=True, db_column='Area_Spl_Pg', null=True)),
                ('doctrate', models.CharField(blank=True, db_column='doctrate', max_length=200, null=True)),
                ('date_doctrate', models.DateField(blank=True, db_column='Date_Doctrate', null=True)),
                ('research_topic_doctrate', models.CharField(blank=True, db_column='Research_topic_doctrate', max_length=50, null=True)),
                ('pass_year_other', models.IntegerField(blank=True, db_column='Pass_Year_Other', null=True)),
                ('cgpa_per_other', models.DecimalField(blank=True, db_column='Cgpa_Per_Other', decimal_places=1, max_digits=5, null=True)),
                ('area_spl_other', models.CharField(blank=True, db_column='Area_Spl_Other', max_length=50, null=True)),
                ('emp_id', models.ForeignKey(db_column='Emp_Id', max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_id_academic', serialize=False, to='login.EmployeePrimdetail', unique=True)),
                ('board_10', models.ForeignKey(blank=True, db_column='Board_10', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board10', to='login.EmployeeDropdown')),
                ('board_12', models.ForeignKey(blank=True, db_column='Board_12', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board12', to='login.EmployeeDropdown')),
                ('degree_other', models.ForeignKey(blank=True, db_column='Degree_Other', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DegreeOther', to='login.EmployeeDropdown')),
                ('degree_pg', models.ForeignKey(blank=True, db_column='Degree_PG', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PG_Degree', to='login.EmployeeDropdown')),
                ('degree_ug', models.ForeignKey(blank=True, db_column='Degree_UG', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UG_Degree', to='login.EmployeeDropdown')),
                ('stage_doctrate', models.ForeignKey(blank=True, db_column='Stage_Doctrate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_doctrate', to='login.EmployeeDropdown')),
                ('univ_dip', models.ForeignKey(blank=True, db_column='Univ_Dip', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiplomaUniversity', to='login.EmployeeDropdown')),
                ('univ_doctrate', models.ForeignKey(blank=True, db_column='Univ_Doctrate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DoctrateUniversity', to='login.EmployeeDropdown')),
                ('univ_other', models.ForeignKey(blank=True, db_column='Univ_Other', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OtherUniversity', to='login.EmployeeDropdown')),
                ('univ_pg', models.ForeignKey(blank=True, db_column='Univ_PG', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PG_University', to='login.EmployeeDropdown')),
                ('univ_ug', models.ForeignKey(blank=True, db_column='Univ_UG', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UG_University', to='login.EmployeeDropdown')),
            ],
            options={
                'db_table': 'employee_academic',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('p_add1', models.CharField(blank=True, db_column='P_Add1', max_length=100, null=True)),
                ('p_add2', models.CharField(blank=True, db_column='P_Add2', max_length=100, null=True)),
                ('p_city', models.CharField(blank=True, db_column='P_City', max_length=30, null=True)),
                ('p_district', models.CharField(blank=True, db_column='P_District', max_length=30, null=True)),
                ('p_pincode', models.CharField(blank=True, db_column='P_Pincode', max_length=10, null=True)),
                ('c_add1', models.CharField(blank=True, db_column='C_Add1', max_length=100, null=True)),
                ('c_add2', models.CharField(blank=True, db_column='C_Add2', max_length=100, null=True)),
                ('c_city', models.CharField(blank=True, db_column='C_City', max_length=30, null=True)),
                ('c_district', models.CharField(blank=True, db_column='C_District', max_length=30, null=True)),
                ('c_pincode', models.CharField(blank=True, db_column='C_Pincode', max_length=10, null=True)),
                ('emp_id', models.ForeignKey(db_column='Emp_Id', max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_id_addr', serialize=False, to='login.EmployeePrimdetail', unique=True)),
                ('c_state', models.ForeignKey(blank=True, db_column='C_State', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CorrespondenceState', to='login.EmployeeDropdown')),
                ('p_state', models.ForeignKey(blank=True, db_column='P_State', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PermanentState', to='login.EmployeeDropdown')),
            ],
            options={
                'db_table': 'employee_address',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocuments',
            fields=[
                ('emp_id', models.ForeignKey(db_column='Emp_Id', max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_id_doc', serialize=False, to='login.EmployeePrimdetail', unique=True)),
                ('marksheet_10', models.CharField(blank=True, db_column='Marksheet_10', max_length=50, null=True)),
                ('marksheet_12', models.CharField(blank=True, db_column='Marksheet_12', max_length=50, null=True)),
                ('marksheet_dip', models.CharField(blank=True, db_column='Marksheet_Dip', max_length=50, null=True)),
                ('marksheet_ug', models.CharField(blank=True, db_column='Marksheet_Ug', max_length=50, null=True)),
                ('marksheet_pg', models.CharField(blank=True, db_column='Marksheet_Pg', max_length=50, null=True)),
                ('marksheet_doctrate', models.CharField(blank=True, db_column='Marksheet_Doctrate', max_length=50, null=True)),
                ('marksheet_other', models.CharField(blank=True, db_column='Marksheet_Other', max_length=50, null=True)),
                ('medical_fitness', models.CharField(blank=True, db_column='Medical_Fitness', max_length=50, null=True)),
                ('character_certificate', models.CharField(blank=True, db_column='Character_Certificate', max_length=50, null=True)),
                ('experience_certificate', models.CharField(blank=True, db_column='Experience_Certificate', max_length=50, null=True)),
            ],
            options={
                'db_table': 'employee_documents',
            },
        ),
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('bank_ac_no', models.CharField(blank=True, db_column='Bank_Ac_No', max_length=25, null=True)),
                ('uan_no', models.CharField(blank=True, db_column='Uan_No', max_length=30, null=True)),
                ('pan_no', models.CharField(blank=True, db_column='Pan_No', max_length=20, null=True)),
                ('aadhar_no', models.CharField(blank=True, db_column='Aadhar_No', max_length=20, null=True)),
                ('pf_deduction', models.CharField(blank=True, db_column='Pf_Deduction', max_length=3, null=True)),
                ('basic', models.DecimalField(blank=True, db_column='Basic', decimal_places=5, max_digits=10, null=True)),
                ('agp', models.DecimalField(blank=True, db_column='Agp', decimal_places=5, max_digits=10, null=True)),
                ('da', models.DecimalField(blank=True, db_column='Da', decimal_places=5, max_digits=10, null=True)),
                ('hra', models.DecimalField(blank=True, db_column='Hra', decimal_places=5, max_digits=10, null=True)),
                ('other_allowances', models.DecimalField(blank=True, db_column='Other_Allowances', decimal_places=5, max_digits=10, null=True)),
                ('mediclaim', models.CharField(blank=True, db_column='Mediclaim', max_length=3, null=True)),
                ('emp_id', models.ForeignKey(db_column='Emp_Id', max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_id_payroll', serialize=False, to='login.EmployeePrimdetail', unique=True)),
                ('salary_type', models.ForeignKey(blank=True, db_column='Salary_Type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SalaryType', to='login.EmployeeDropdown')),
            ],
            options={
                'db_table': 'employee_payroll',
            },
        ),
        migrations.CreateModel(
            name='EmployeePerdetail',
            fields=[
                ('fname', models.CharField(blank=True, db_column='FName', max_length=50, null=True)),
                ('mname', models.CharField(blank=True, db_column='MName', max_length=50, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('emp_id', models.ForeignKey(db_column='Emp_Id', max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_id_per', serialize=False, to='login.EmployeePrimdetail', unique=True)),
                ('bg', models.ForeignKey(blank=True, db_column='Bg', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BloodGroup', to='login.EmployeeDropdown')),
                ('caste', models.ForeignKey(blank=True, db_column='Caste', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caste', to='login.EmployeeDropdown')),
                ('gender', models.ForeignKey(blank=True, db_column='Gender', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Gender', to='login.EmployeeDropdown')),
                ('marital_status', models.ForeignKey(blank=True, db_column='Marital_status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marital_status', to='login.EmployeeDropdown')),
                ('nationality', models.ForeignKey(blank=True, db_column='Nationality', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nationality', to='login.EmployeeDropdown')),
                ('religion', models.ForeignKey(blank=True, db_column='Religion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='religion', to='login.EmployeeDropdown')),
            ],
            options={
                'db_table': 'employee_perdetail',
            },
        ),
        migrations.CreateModel(
            name='EmployeeResearch',
            fields=[
                ('research_years', models.IntegerField(blank=True, db_column='Research_Years', null=True)),
                ('research_months', models.IntegerField(blank=True, db_column='Research_Months', null=True)),
                ('industry_years', models.IntegerField(blank=True, db_column='Industry_Years', null=True)),
                ('industry_months', models.IntegerField(blank=True, db_column='Industry_Months', null=True)),
                ('teaching_years', models.IntegerField(blank=True, db_column='Teaching_Years', null=True)),
                ('teaching_months', models.IntegerField(blank=True, db_column='Teaching_Months', null=True)),
                ('emp_id', models.ForeignKey(db_column='Emp_Id', max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_id_research', serialize=False, to='login.EmployeePrimdetail', unique=True)),
            ],
            options={
                'db_table': 'employee_research',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSeparation',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=15, null=True)),
                ('rejoin_date', models.DateField(blank=True, db_column='Rejoin_Date', null=True)),
                ('emp_remark', models.CharField(blank=True, db_column='Emp_Remark', max_length=5000, null=True)),
                ('hod_status', models.CharField(blank=True, db_column='HOD_Status', max_length=15, null=True)),
                ('hod_remark', models.CharField(blank=True, db_column='HOD_Remark', max_length=5000, null=True)),
                ('hr_status', models.CharField(blank=True, db_column='HR_Status', max_length=15, null=True)),
                ('hr_remark', models.CharField(blank=True, db_column='HR_Remark', max_length=5000, null=True)),
                ('final_status', models.CharField(blank=True, db_column='Final_Status', max_length=15, null=True)),
                ('attachment', models.CharField(blank=True, db_column='Attachment', max_length=50, null=True)),
                ('emp_id', models.ForeignKey(blank=True, db_column='Emp_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_id_sepration', to='login.EmployeePrimdetail')),
                ('type', models.ForeignKey(blank=True, db_column='Type', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.EmployeeDropdown')),
            ],
            options={
                'db_table': 'employee_separation',
            },
        ),
        migrations.CreateModel(
            name='NoDuesEmp',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=15, null=True)),
                ('emp_id', models.ForeignKey(blank=True, db_column='Emp_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_id_due', to='login.EmployeePrimdetail')),
                ('head_id', models.ForeignKey(blank=True, db_column='Head_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_id_head', to='login.EmployeePrimdetail')),
            ],
            options={
                'db_table': 'no_dues_employee',
            },
        ),
        migrations.CreateModel(
            name='NoDuesHead',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Status', default='ACTIVE', max_length=15)),
                ('due_head', models.ForeignKey(blank=True, db_column='Due_Head', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodue_head', to='login.EmployeeDropdown')),
                ('emp_id', models.ForeignKey(blank=True, db_column='Emp_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodue_emp', to='login.EmployeePrimdetail')),
            ],
            options={
                'db_table': 'no_dues_head',
            },
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('reporting_no', models.IntegerField(blank=True, db_column='Reporting_No', null=True)),
                ('department', models.ForeignKey(blank=True, db_column='Department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Department', to='login.EmployeeDropdown')),
                ('emp_id', models.ForeignKey(db_column='Emp_Id', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id_rep', to='login.EmployeePrimdetail')),
                ('reporting_to', models.ForeignKey(blank=True, db_column='Reporting_To', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Designation', to='login.EmployeeDropdown')),
            ],
            options={
                'db_table': 'reporting',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('emp_id', models.ForeignKey(db_column='Emp_Id', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id_role', to='login.EmployeePrimdetail')),
                ('roles', models.ForeignKey(blank=True, db_column='roles', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='login.EmployeeDropdown')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('intime', models.TimeField(blank=True, db_column='intime', max_length=10, null=True)),
                ('outtime', models.TimeField(blank=True, db_column='outtime', max_length=10, null=True)),
                ('latein', models.TimeField(blank=True, db_column='lateIn', max_length=10, null=True)),
                ('earlyexit', models.TimeField(blank=True, db_column='earlyExit', max_length=10, null=True)),
                ('fulldaytime', models.TimeField(blank=True, db_column='fullDayTime', max_length=10, null=True)),
                ('halfdaytime', models.TimeField(blank=True, db_column='halfDayTime', max_length=10, null=True)),
                ('breakstart', models.TimeField(blank=True, db_column='breakStart', max_length=10, null=True)),
                ('breakend', models.TimeField(blank=True, db_column='breakEnd', max_length=10, null=True)),
                ('shiftid', models.ForeignKey(blank=True, db_column='shiftId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_shift', to='login.EmployeeDropdown')),
            ],
            options={
                'db_table': 'shifts',
            },
        ),
    ]
